version: "3.9"
services:
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: revivios-db
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - 5432:5432

    turbo:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - 8000:8000
