version: "3.8"
services:
    db:
        container_name: db
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: revivios
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    turbo:
        container_name: turbo
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - "8000:8000"
